task: "sentiment"

nlp_model_name: "monologg/koelectra-small-v3-discriminator"
llm_model_name: "exaone3.5"
cuda: true

# file names
raw_data_file: "reviews.csv"
dataset_file: "dataset.jsonl"
train_file: "train.jsonl"
test_file: "test.jsonl"

# Category for Sentiment Analysis labels
category:
  - "주차"
  - "화장실"
  - "시설관리"
  - "혼잡도"
  - "접근성"
  - "편의시설"
  - "가성비"
  - "아이 동반"
  - "노약자 동반"
  - "장소"
  - "활동"

# Sentiment labels
label_list:
  - "pos"
  - "neg"
  - "none"

# Dataset Generation parameters
split:
  train_ratio: 0.8
  dev_ratio: 0.1
  seed: 42
num_workers: 4

# K-Fold parameters
kfold_num: 5
kfold_seed: 42

# Training parameters
max_seq_len: 256
train_batch_size: 32
eval_batch_size: 64
max_steps: 0
epochs: 3
gradient_accumulation_steps: 1
weight_decay: 0.01
learning_rate: 5e-5
adam_epsilon: 1e-8
warmup_proportion: 0.1
max_grad_norm: 1.0
early_stopping_patience: 3

# Evaluation parameters
eval_num_workers: 4

# Huggingface Hub parameters
hf_repo_name: "CBNU-013A/piknlp-sentiment"  # Huggingface Hub 저장소 이름

